version: "2"

linters:
  disable:
    - errcheck
    - gosec
    - nakedret
    - wrapcheck
    - exhaustruct
    - revive
    - gocyclo
    - funlen
    - dupl
    - mnd
    - godot
    - nlreturn
    - wsl
    - gocritic
    - bodyclose
    - noctx
    - staticcheck
