package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/charmbracelet/lipgloss"
	"github.com/spf13/cobra"
)

func newHardenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "harden",
		Short: "Automatically generate repository security configurations",
		Long:  `Generates standard security boilerplate to protect your repository, including SECURITY.md, dependabot.yml, CodeQL workflows, and secret scanning configs.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runHarden()
		},
	}
	return cmd
}

func runHarden() error {
	titleStyle := lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("#FFD700"))
	successStyle := lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("#00FF87"))
	dimStyle := lipgloss.NewStyle().Foreground(lipgloss.Color("#888888"))

	fmt.Println()
	fmt.Println(titleStyle.Render("🛡️  AutoDev Repository Hardening"))
	fmt.Println(dimStyle.Render("  Generating security boilerplate files..."))
	fmt.Println()

	filesToGenerate := map[string]string{
		"SECURITY.md": `# Security Policy

## Supported Versions

Please check below for the supported versions of this project.

| Version | Supported          |
| ------- | ------------------ |
| 1.0.x   | :white_check_mark: |
| < 1.0   | :x:                |

## Reporting a Vulnerability

Please report security issues directly to the maintainers via email. Do not open public issues for security vulnerabilities.
`,
		".github/dependabot.yml": `version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
`,
		".github/workflows/codeql.yml": `name: "CodeQL"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * 0'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: go, javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
`,
		".gitleaks.toml": `title = "gitleaks config"
# Basic Gitleaks Config generated by AutoDev
[allowlist]
description = "Global allowlist"
paths = [
    '''gitleaks\.toml''',
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|png|jpeg)'''
]
`,
		".pre-commit-config.yaml": `repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
    -   id: gitleaks
`,
	}

	for path, content := range filesToGenerate {
		if err := writeFileSafely(path, content); err != nil {
			if err.Error() == "file already exists" {
				fmt.Println(lipgloss.NewStyle().Foreground(lipgloss.Color("#FFD700")).Render(fmt.Sprintf("  ⚠ Skipped %s (already exists)", path)))
			} else {
				fmt.Println(lipgloss.NewStyle().Foreground(lipgloss.Color("#FF6B6B")).Render(fmt.Sprintf("  ✗ Failed to create %s: %v", path, err)))
			}
		} else {
			fmt.Println(successStyle.Render(fmt.Sprintf("  ✓ Created %s", path)))
		}
	}

	fmt.Println()
	fmt.Println(successStyle.Render("  Repository successfully hardened!"))
	fmt.Println(dimStyle.Render("  Review the generated files and commit them to your repository."))
	fmt.Println()
	return nil
}

func writeFileSafely(path string, content string) error {
	if _, err := os.Stat(path); err == nil {
		// File already exists, don't overwrite blindly
		// For a more advanced version, we could prompt, but for V1 we skip existing files.
		return fmt.Errorf("file already exists")
	}

	dir := filepath.Dir(path)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}

	return os.WriteFile(path, []byte(content), 0644)
}
